Repository cBridges851/tkinter-image-viewer, pull requests merged in 2022-10, with the labels that each got.

#9 added requirements.txt and updated README.md #7
  README.md
  requirements.txt
Labels: documentation, hacktoberfest, hacktoberfest2022

#8 Added menu that allows opening folders, and viewing the images within.
  image-viewer.py
Labels: hacktoberfest, hacktoberfest2022

#15 Light mode
  image-viewer.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 Adds support for opening files
  image-viewer.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 Update image-viewer.py
  image-viewer.py
Labels: bug, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#29 Solve Move hard-coded UI strings to a JSON File #28
  image-viewer.py
  image_handler.py
  lang/en-GB.json
  menu.py
  settings/default_display_settings.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Saving themes implemented and packaged the project into single module
  Image_Viewer/favicon.ico
  Image_Viewer/file_handler.py
  Image_Viewer/image-viewer.png
  Image_Viewer/image_handler.py
  Image_Viewer/image_viewer.py
  Image_Viewer/images/animal crossing.jpg
  Image_Viewer/images/code camp.jpg
  Image_Viewer/images/squirrel 1.jpg
  Image_Viewer/images/squirrel 2.jpg
  Image_Viewer/images/squirrel 3.jpg
  Image_Viewer/images/squirrel 4.jpg
  Image_Viewer/images/train 1.jpg
  Image_Viewer/images/train 2.jpg
  Image_Viewer/images/train 3.jpg
  Image_Viewer/images/train 4.jpg
  Image_Viewer/images/train 5.jpg
  Image_Viewer/lang/en-GB.json
  Image_Viewer/menu.py
  Image_Viewer/navigator.py
  Image_Viewer/orchestrator.py
  Image_Viewer/renderer.py
  Image_Viewer/settings/customSettings.json
  Image_Viewer/settings/default_display_settings.json
  Image_Viewer/settings/themes.json
  Image_Viewer/theme.py
  Image_Viewer/themes_enum.py
  README.md
  run.py
  setup.py
  theme.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
